// Cloudflare Worker — TempMail API + Email Inbound Handler
// Uses predefined username pool for email generation

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

const EMAIL_TTL = 1800;     // 30 minutes — email content expires
const ADDRESS_TTL = 31536000; // 1 year — address persists (effectively permanent)

const USERNAME_POOL = [
  "aceh.aldi900",
  "aceh.bulma297",
  "aceh31954",
  "aceh_xcv",
  "acehid183",
  "acehmadiun522",
  "acehx637",
  "acehzone2148",
  "aditya67700",
  "adityakun3235",
  "adityapro8099",
  "agung.victoryrush374",
  "agung.ya",
  "agung_dev",
  "agung_shinobu814",
  "agung_silentkiller798",
  "aimbot.2007",
  "aimbot.max",
  "aimbot47400",
  "aimbot_2019",
  "aimbot_robin28",
  "aimbotid",
  "aimbotpro",
  "aimbotsan",
  "akaza.ambon808",
  "akaza_x",
  "aldi.2017",
  "aldi_store",
  "alya.2014",
  "alya.pro9046",
  "alya52403",
  "alya_2007",
  "alya_store4429",
  "alyasubang757",
  "alyax",
  "alyax8085",
  "ambon.2023",
  "ambon.dx",
  "ambon17950",
  "ambon49896",
  "ambon_2026",
  "ambon_play",
  "ambonchan",
  "amelia.zone",
  "ameliasan8613",
  "andika.2015",
  "andika.ilham527",
  "andika.kun3322",
  "andika_id187",
  "andika_phy",
  "andika_qjhg",
  "andikazenitsu563",
  "arif.2013",
  "arif.iiq",
  "arifgojo198",
  "arifta",
  "armin.fitri384",
  "armin_2014",
  "armin_nami557",
  "armin_pro",
  "armin_salsa85",
  "ayu.play5935",
  "ayu.x",
  "ayu2001",
  "ayu_kun",
  "ayuwlv",
  "bagas.2015",
  "bagas92227",
  "bagas_kun",
  "bagas_pasuruan626",
  "bagasdev",
  "bagasrani677",
  "bagasvpan",
  "bagasxk",
  "bali.dev",
  "bali.dng",
  "bali.hunterz695",
  "bali38740",
  "bali_dev287",
  "bali_max",
  "balihd",
  "balikpapan.id9603",
  "balikpapan.inosuke456",
  "balikpapan.max",
  "balikpapan.store7349",
  "balikpapan81217",
  "balikpapan_fz",
  "balikpapan_real",
  "bandung.real",
  "bandung32967",
  "bandung_dev3056",
  "banten3759",
  "banten62452",
  "banyuwangi.fajar784",
  "banyuwangi80602",
  "banyuwangi_firestorm221",
  "banyuwangitanjiro10",
  "banyuwangivenomstrike745",
  "batam.bcce",
  "batam.gz",
  "batam_pro",
  "batamhunterz880",
  "batamlaw92",
  "batamxy",
  "battleborn.dkw",
  "battleborn.mtc",
  "battleborn53594",
  "battlebornproplayer195",
  "battlebornpry",
  "bayu.dev4440",
  "bayu39834",
  "bayu_xt",
  "beerus.eayp",
  "beerus.real",
  "beerus36886",
  "beerus_store",
  "beerusbogor841",
  "bekasi2009",
  "bekasi_2025",
  "bekasinurul875",
  "bima.store2359",
  "bima34168",
  "bima53628",
  "bima_rama463",
  "bimairfan508",
  "binjai.arif791",
  "binjai.kun",
  "binjai2018",
  "binjai51704",
  "binjai73553",
  "blackmamba.zenitsu568",
  "blackmamba33624",
  "blackmambaalya930",
  "blastcore.chan6871",
  "blastcore.fitri2",
  "blastcore.jrl",
  "blastcore.sarah492",
  "blastcore86920",
  "blastcore_anqn",
  "blastcore_id1240",
  "blastcore_x",
  "blastcoretrunks716",
  "bogor.2015",
  "bogor.2024",
  "bogor10473",
  "bogor54192",
  "bogor70236",
  "bogorkym",
  "bossfight.kun1501",
  "bossfight.rengoku980",
  "bossfight2008",
  "bossfight_2020",
  "bossfightid3740",
  "broly53106",
  "broly_2019",
  "broly_2022",
  "broly_2026",
  "broly_chan",
  "brolysan",
  "brolysurabaya88",
  "brolyuh",
  "bulma89070",
  "bulma_jayapura948",
  "bulma_play9201",
  "bulmaphq",
  "cilacap.2002",
  "cilacap_nk",
  "cilacap_play8432",
  "cilacapchan",
  "cilegon.muzan322",
  "cilegon82297",
  "cirebon.2015",
  "cirebon.play",
  "cirebon_dev357",
  "citra.denpasar261",
  "citra_idrm",
  "citrads",
  "citrafv",
  "citrarizky574",
  "clutchking85121",
  "clutchking97477",
  "clutchking_2005",
  "clutchkingpro3506",
  "crimsonrage45600",
  "crimsonrage_pro",
  "crimsonrage_x",
  "cyberwolf.2009",
  "cyberwolf.zone",
  "cyberwolf.zone7580",
  "cyberwolf11414",
  "cyberwolf59278",
  "cyberwolfdev5968",
  "cyberwolfshadowhunter343",
  "darkknight.ghostblade15",
  "darkknight_zone5303",
  "darkknightpro504",
  "darkknightzaki585",
  "darkviper2018",
  "darkviper2024",
  "darkviper_real4177",
  "darkviperchan7870",
  "darkvipergenos820",
  "darkviperid",
  "deathwalker13357",
  "deathwalker2002",
  "deathwalker2014",
  "deathwalkerdev",
  "denpasar.battleborn685",
  "denpasar.pro",
  "denpasar.xd",
  "denpasar_2011",
  "denpasar_kupang108",
  "denpasarpro9554",
  "denpasarzone3243",
  "depok.2020",
  "depok.dev1217",
  "depok.play",
  "depok_2018",
  "dewi.2014",
  "dewi.2015",
  "dewi2017",
  "dewi42833",
  "dewi_ie",
  "dewi_magelang253",
  "dewi_zone653",
  "dewigaming",
  "dimas.pro",
  "dimas.ranker744",
  "dimas_rgv",
  "dimasgresik349",
  "dimasttj",
  "dinda.2013",
  "dinda.2014",
  "dinda.yuji262",
  "dinda2018",
  "dinda4404",
  "dinda_chan",
  "dindadev8960",
  "dindaragequit829",
  "dindarapidfire277",
  "dragonlord.chan6111",
  "dragonlord.yi",
  "dragonlord_dev6222",
  "dragonlord_official",
  "dragonlordmax",
  "epicgamer.cirp",
  "epicgamer.rengoku911",
  "epicgamer85602",
  "epicgamermagelang951",
  "eren.nipr",
  "eren2007",
  "eren2017",
  "eren_2006",
  "erendev758",
  "erenshanks997",
  "fajar.max",
  "fajar2024",
  "fajar46370",
  "fajar_dz",
  "fajar_kun",
  "fajar_obito78",
  "farhan.2012",
  "farhan.genos151",
  "farhan.qpt",
  "farhan.yogyakarta276",
  "farhan22175",
  "farhan51494",
  "farhan_2003",
  "farhan_dqf",
  "farhan_ogg",
  "farhan_store",
  "fikri.gaming7995",
  "fikri93626",
  "fikri_official2430",
  "finalhit.2008",
  "finalhit1155",
  "finalhit_asma",
  "firestorm.vakh",
  "firestorm_2015",
  "firestorm_aye",
  "fitri.dwu",
  "fitri2001",
  "fitri_gaming",
  "fitrimk",
  "flameking.2009",
  "flameking97546",
  "flameking_play",
  "flamekingkakashi279",
  "flamekingsan",
  "frieza.kun1095",
  "frieza.real",
  "frieza_real",
  "friezavsdw",
  "frostbite.gaming",
  "frostbite.kun",
  "frostbite.tpk",
  "frostbite32570",
  "frostbite39016",
  "frostbite49488",
  "frostbite60719",
  "frostbite_official1556",
  "galih.chan2532",
  "galih.zone2358",
  "galih_play",
  "galih_play4084",
  "galih_real",
  "galihshadowfox831",
  "garut7066",
  "garut94383",
  "garutpiccolo877",
  "garutsan9334",
  "genos.chan7049",
  "genos.kzde",
  "genos.muzan783",
  "genos.real",
  "genos2026",
  "genos21957",
  "genos29692",
  "genos_qqwv",
  "genos_zone7812",
  "genosgalih83",
  "ghostblade152",
  "ghostbladenezuko65",
  "ghostbladereal",
  "giyu2022",
  "giyu_bogor16",
  "gohan.nv",
  "gohan_ultrakill907",
  "gohan_zone2369",
  "gohanid",
  "gojo46709",
  "gojogaming",
  "gojoid",
  "goku.kun",
  "goku46239",
  "goku_pro2278",
  "goku_toxicvenom250",
  "gresik.fvut",
  "gresik.gx",
  "gresik.xp",
  "gresik28715",
  "gresikgoku838",
  "gresikkun8174",
  "hafid.dev9506",
  "hafid.max6587",
  "hafid98944",
  "hafid_eren529",
  "hafid_gaming7792",
  "hafid_play",
  "hafidiec",
  "hafidujc",
  "hasan.2024",
  "hasan.ky",
  "hasan.tc",
  "hasan_dev",
  "hasaneq",
  "hasanhunterz874",
  "hasanmky",
  "headshot1399",
  "headshot_wvga",
  "headshotzone4273",
  "hinata.bayu281",
  "hinata.real6905",
  "hinata.x",
  "hinata20904",
  "hinata_id",
  "hinata_store4074",
  "hinatamadara144",
  "hunterz.qal",
  "hunterz2025",
  "hunterz38391",
  "hunterz55407",
  "hunterz_store7052",
  "hunterzpwgc",
  "icephoenix2021",
  "icephoenix83457",
  "icephoenix_flameking101",
  "icephoenix_official",
  "icephoenix_real3769",
  "icephoenix_san8592",
  "ilham2018",
  "ilham_dev",
  "ilhambroly496",
  "inosuke2021",
  "inosuke59872",
  "inosuke_apmg",
  "inosuke_kun1018",
  "intan.2000",
  "intan.obito361",
  "intan.real",
  "intan.vina147",
  "intan22934",
  "intan47141",
  "intan_sv",
  "intanx9520",
  "irfan.banten217",
  "irfan_official",
  "irfan_ve",
  "irfangax",
  "irfanht",
  "ironfist.id",
  "ironfist2006",
  "ironfist85946",
  "ironfist_kun496",
  "ironfistx",
  "itachi.dev3712",
  "itachi43909",
  "itachi64557",
  "itachi_2024",
  "itachisan3691",
  "jakarta.jfxj",
  "jakarta.zombiehunter311",
  "jakarta_kb",
  "jakarta_store913",
  "jakartapro",
  "jakartaqupq",
  "jayapura.kun644",
  "jayapura.max2777",
  "jayapura63319",
  "jayapura71743",
  "jayapurabali26",
  "jayapuragaming",
  "jayapuraofficial",
  "jayapuraqxtu",
  "jayapuratim",
  "jember.2019",
  "jember.jlf",
  "jiraiya.2008",
  "jiraiya2015",
  "jiraiyachan",
  "kaido.2016",
  "kaido.play",
  "kaido_dev",
  "kakashi.dev4846",
  "kakashi.mzbk",
  "kakashi2019",
  "karawang.cilegon370",
  "karawang2025",
  "karawang67657",
  "karawang81002",
  "karawang_official4462",
  "karawang_piccolo315",
  "karawanghkym",
  "karawangid",
  "kediri.gaming9470",
  "kediri16224",
  "kediri60081",
  "kediri_2014",
  "kediri_id4829",
  "kedirigaming7749",
  "kingpush_2016",
  "kingpush_cku",
  "kingpush_id229",
  "kingpush_san",
  "kingpush_wzux",
  "kingpushgojo301",
  "kingpushnurul637",
  "kingpushpd",
  "kingpushqwv",
  "krillin2011",
  "krillin59561",
  "krillin_x9235",
  "kupang.id",
  "kupang.real7611",
  "kupang.ubah",
  "kupang2000",
  "kupang2023",
  "kupang74754",
  "kupang_subang682",
  "kupangvhq",
  "law.2012",
  "law.gaming",
  "law16314",
  "lawputri60",
  "levi.dev6703",
  "levi.medan265",
  "levi.x",
  "levi38582",
  "levi86510",
  "levi_chan",
  "lina2015",
  "lombok23560",
  "lombok34746",
  "lombok_dev",
  "luckystar.zone",
  "luckystar83167",
  "luckystar_2010",
  "luckystartrunks236",
  "luffy.aow",
  "luffy2001",
  "luffy2009",
  "luffyyfuh",
  "madara25827",
  "madara64339",
  "madara75265",
  "madara_fa",
  "madara_zone",
  "madarareal6320",
  "madiun.chan",
  "madiun.naruto706",
  "madiun57551",
  "madiun_2001",
  "madiun_2007",
  "madiun_2009",
  "madiunuag",
  "magelang.malang453",
  "magelang.real",
  "magelang.shanks753",
  "magelang2019",
  "magelang36517",
  "magelang9768",
  "magelang_li",
  "makassar.kygr",
  "makassar.raka760",
  "makassar.real",
  "makassar.store9231",
  "makassar2023",
  "makassar_2008",
  "makassar_farhan926",
  "makassar_store",
  "makassarfinalhit426",
  "makassarvg",
  "malang.2014",
  "malang.firestorm453",
  "malang14805",
  "malang_hei",
  "malang_pro8356",
  "manado.2019",
  "manado.chan2305",
  "manado.dev",
  "manado45620",
  "manado_madara313",
  "maya10613",
  "maya11046",
  "maya_dev9743",
  "medan.2011",
  "medan.hunterz351",
  "medan96125",
  "megadragon19827",
  "megumi.chan",
  "megumi.san7208",
  "megumilaw343",
  "megumilgz",
  "megumiqy",
  "megumisoag",
  "megumix",
  "mikasa_pro3092",
  "mikasagaming171",
  "minato41874",
  "minato51119",
  "minato72844",
  "minato_2001",
  "minato_genos174",
  "minato_sasuke765",
  "minatomax",
  "minatoofficial9326",
  "minatorq",
  "mitsuri9715",
  "mitsuriazh",
  "mitsurichan",
  "mitsurizvx",
  "muzan_2002",
  "muzan_gww",
  "muzan_max1339",
  "muzan_san5336",
  "nabila2015",
  "nabila23923",
  "nabila_aso",
  "nabila_gaming9267",
  "nabila_gunp",
  "nabila_san7023",
  "nabila_zb",
  "nadia30885",
  "nadia_kun2776",
  "nadia_pro2290",
  "nami.chan",
  "nami.makassar147",
  "nami2021",
  "namiprobolinggo855",
  "nanda_battleborn203",
  "nandabekasi43",
  "nandaofficial9707",
  "naruto2001",
  "naruto_2008",
  "naruto_2016",
  "naruto_stealthninja704",
  "naruto_surabaya843",
  "narutohunterz353",
  "narutokun",
  "neonblade.2026",
  "neonblade_x",
  "neonbladestore",
  "nezuko.max3924",
  "nezuko_dev",
  "nightmare_id",
  "nightmare_real",
  "nightmaremax",
  "nightmarepro",
  "nightwolf.max",
  "nightwolf.ur",
  "nightwolf_2003",
  "nightwolf_x",
  "nightwolfbali180",
  "nightwolfreal4007",
  "nobara.nobara400",
  "nobara.store9364",
  "nobara18130",
  "nobara_2013",
  "nobarapro8459",
  "nobaraui",
  "noobmaster.kingpush521",
  "noobmasterkun",
  "nurul.x9994",
  "nurul2002",
  "nurul_2015",
  "nurulreal",
  "nurulsan",
  "obito.aceh970",
  "obito_gaming5207",
  "obito_real4655",
  "obito_san4883",
  "obitopalembang176",
  "obitozone",
  "padang.bpgj",
  "padang.jk",
  "padang.kha",
  "padang.rendy491",
  "padang91808",
  "padang_official3067",
  "padang_store9287",
  "palembang_hasan978",
  "palembang_san307",
  "palembangmifz",
  "palembangtuv",
  "papua50030",
  "papua70854",
  "papua_2003",
  "papuahl",
  "papuakxx",
  "pasuruan_dev4917",
  "pasuruan_max",
  "pasuruan_pro4074",
  "pekanbaru55434",
  "pekanbaru_putri232",
  "pekanbarufarhan22",
  "pekanbarusan",
  "piccolo.2016",
  "piccolo.iqoa",
  "piccolo.trunks615",
  "piccolo39037",
  "piccolo_xq",
  "piccolo_zone",
  "piccolochan",
  "piccolofyhc",
  "piccolostore",
  "pontianak2011",
  "pontianakshinobu366",
  "probolinggo.chan",
  "probolinggo_kun637",
  "probolinggohs",
  "proplayer.x",
  "proplayer_real4078",
  "proplayermakassar839",
  "purwakarta.balikpapan995",
  "purwakarta.dwmu",
  "purwakarta35526",
  "purwakarta42824",
  "purwakarta79327",
  "purwakartazone",
  "putra.kun",
  "putra58481",
  "putra_2021",
  "putra_play161",
  "putra_silentkiller489",
  "putri.real5090",
  "putri.taf",
  "putri2023",
  "putri73366",
  "putrigaming1115",
  "putriid966",
  "putrireal5517",
  "putristore",
  "putrizone",
  "rafi.gojo661",
  "rafi.store",
  "rafi_2023",
  "ragequit7232",
  "ragequit84941",
  "ragequit_fe",
  "ragequit_kun6427",
  "ragequit_yusuf694",
  "raka.real",
  "raka28573",
  "raka94833",
  "raka_2017",
  "raka_official",
  "rama.id7496",
  "rama12650",
  "rama_2012",
  "rama_ofy",
  "rama_vual",
  "ramanurul413",
  "rani.yuji262",
  "rani2000",
  "rani_x4517",
  "raniegjm",
  "ranikun",
  "ranker.dev",
  "ranker_2003",
  "ranker_cllp",
  "ranker_kun7042",
  "rapidfire.x",
  "rapidfire2016",
  "rapidfirechan",
  "rapidfiretm",
  "rapidfirexgq",
  "rapidfirezone2560",
  "redsniper.2010",
  "redsniper.kingpush232",
  "redsniper2006",
  "redsniper2020",
  "redsniper78638",
  "redsniper_nioc",
  "redsniperbagas792",
  "redsniperpro2981",
  "rendy.sh",
  "rendy_ns",
  "rendynaruto843",
  "rendysjf",
  "rengoku.official3177",
  "rengoku.official5992",
  "rengoku16549",
  "rengokugaming",
  "reza.2008",
  "reza.gohan418",
  "reza.san",
  "reza.surabaya270",
  "reza2002",
  "reza23418",
  "reza_official8288",
  "reza_ucnw",
  "rezachan8562",
  "rezakun9365",
  "rezalzfx",
  "ridho_official4132",
  "ridho_vwfk",
  "rizky.gaming",
  "rizky.play",
  "rizky.qj",
  "rizky2000",
  "rizky_aj",
  "rizky_chan",
  "rizkyzone4190",
  "robin.smok",
  "robin_id5237",
  "robin_vina966",
  "robinplay2123",
  "robinxyb",
  "sabo.dev",
  "sabo.id7139",
  "sabo.oowc",
  "sabo.zu",
  "sabo_real2723",
  "sabo_store8281",
  "sabokz",
  "saitama_fqk",
  "saitamakun1564",
  "saitamapro3782",
  "saitamazone",
  "sakura67661",
  "sakuragaming8656",
  "sakuraplay",
  "salsa20641",
  "salsa_2016",
  "salsa_max",
  "salsa_official4983",
  "salsabwk",
  "salsaofficial",
  "samarinda.max",
  "samarinda.official3966",
  "samarinda.official6239",
  "samarinda.pro9401",
  "samarinda.voidwalker974",
  "samarinda20190",
  "samarinda26623",
  "samarinda70663",
  "samarinda_depok20",
  "sanji2021",
  "sanji_fjg",
  "sanji_store510",
  "sanji_zone",
  "sanjix",
  "sarah.greh",
  "sarah.id7449",
  "sarah.x109",
  "sarah2014",
  "sarah57251",
  "sarah58391",
  "sarah89386",
  "sarah90053",
  "sasuke.2013",
  "sasuke.yj",
  "sasuke2013",
  "sasuke421",
  "sasuke_af",
  "semarang_egw",
  "semarangagz",
  "semarangbeerus478",
  "serang.zaki890",
  "serang_x531",
  "serangyb",
  "shadowfox.chan",
  "shadowfox30327",
  "shadowfox_official9417",
  "shadowfox_play6045",
  "shadowfox_qipe",
  "shadowfoxkun8187",
  "shadowhunter.2019",
  "shadowhunter.shadowhunter508",
  "shadowhunter56770",
  "shadowhunter57596",
  "shadowhunter84013",
  "shadowhunter_chan",
  "shadowhunter_play",
  "shanks67013",
  "shanks_2015",
  "shanks_store",
  "shanksig",
  "shankskun",
  "shinobu.2003",
  "shinobu.2022",
  "shinobu.wyi",
  "shinobu2017",
  "shinobu_piccolo48",
  "shinobu_real",
  "sidoarjo.muzan344",
  "sidoarjo84723",
  "sidoarjo_bali323",
  "sidoarjomax7437",
  "sidoarjox6352",
  "silentkiller.2007",
  "silentkiller.2025",
  "silentkiller.wugo",
  "silentkiller.x",
  "silentkiller45364",
  "silentkiller61521",
  "silentkiller69965",
  "silentkiller_wh",
  "silentkillerisu",
  "siti.hr",
  "siti2018",
  "siti36004",
  "siti_2026",
  "siti_max5559",
  "sitidev",
  "sitihet",
  "sitizone",
  "skyrider.id5379",
  "skyrider50435",
  "skyriderkun3765",
  "skyriderreal6796",
  "solo.official",
  "solo44944",
  "solo_dev",
  "solo_play1680",
  "soloed",
  "soulreaper.dev2783",
  "soulreaper77677",
  "soulreaperpekanbaru704",
  "speedrun.goku519",
  "speedrun.ihj",
  "speedrun61831",
  "speedrun_play",
  "speedrun_vtqk",
  "speedrunqfu",
  "stealthninja.2009",
  "stealthninja.sukabumi317",
  "stealthninja35969",
  "stealthninja_rczy",
  "stormbreaker81936",
  "stormbreaker_beerus967",
  "stormbreaker_law278",
  "stormbreakersabo117",
  "subang.balikpapan155",
  "subang.neonblade482",
  "subang.san",
  "subang_sarah318",
  "subangofficial",
  "sukabumi2026",
  "sukabumi_2016",
  "surabaya2017",
  "surabaya_kun",
  "surabaya_official",
  "surabayastore",
  "surabayazxvn",
  "tangerang_2002",
  "tangerangzone5173",
  "tanjiro71070",
  "tanjiro72970",
  "tanjiro_sidoarjo67",
  "tanjirocitra248",
  "tanjiroeren397",
  "tanjiroufi",
  "tasik.irfan822",
  "tasik16220",
  "tasik76907",
  "tasik_2015",
  "tasik_chan1271",
  "tasik_soulreaper886",
  "thunderbolt.kun4303",
  "thunderbolt14214",
  "thunderbolt4260",
  "thunderbolt_2024",
  "thunderbolt_wg",
  "thunderboltdev3601",
  "thunderbolttuk",
  "tiara.2019",
  "tiara.store",
  "tiara_2009",
  "tiara_cl",
  "tiara_dev6277",
  "toxicvenom12496",
  "toxicvenom_armin202",
  "toxicvenom_rani452",
  "trunks.2026",
  "trunks.dimas782",
  "trunks.real5564",
  "trunkschan",
  "trunksputra955",
  "trunkszw",
  "ultrakill_aditya975",
  "ultrakill_mz",
  "vegeta2015",
  "vegeta_cfmq",
  "vegeta_rengoku334",
  "vegeta_zombiehunter783",
  "vegetamax",
  "venomstrike_2014",
  "venomstrike_fajar847",
  "victoryrush.makassar647",
  "victoryrush43888",
  "victoryrush61454",
  "victoryrush79560",
  "victoryrush_official8849",
  "vina.armin167",
  "vina_max6867",
  "vina_play8682",
  "voidwalker.x5891",
  "voidwalker3480",
  "voidwalker_2000",
  "voidwalker_real2311",
  "voidwalker_tmq",
  "voidwalkercilegon400",
  "wahyu54533",
  "wahyu_papua36",
  "wahyucyberwolf658",
  "warriorx.max",
  "warriorx.speedrun65",
  "warriorx.zone",
  "warriorx_gaming5009",
  "warriorx_jakarta147",
  "warriorx_vz",
  "warriorxzone",
  "wildan.bima594",
  "wildan.darkviper176",
  "wildan.gaming2309",
  "wildan57262",
  "yogyakarta.2007",
  "yogyakarta.id",
  "yogyakarta.kp",
  "yogyakarta.store",
  "yuji.chan",
  "yuji.play",
  "yuji.xuuq",
  "yusuf.2023",
  "yusuf.gaming4126",
  "yusuf24296",
  "yusuf69332",
  "yusuf_2026",
  "yusuf_dev9221",
  "yusuf_play8828",
  "yusufgaming9454",
  "yusufpro",
  "zaki.max",
  "zenitsu.id",
  "zenitsu.yn",
  "zenitsu44544",
  "zenitsurbyj",
  "zombiehunter.id3800",
  "zombiehunter.ke",
  "zombiehunter64859",
  "zombiehunter8525",
  "zombiehunter_play9281",
  "zombiehunterxum",
  "zoro.frieza950",
  "zoro22480",
  "zoro35164",
  "zoro36867",
  "zoro99459",
  "zoro_syf"
];

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", ...CORS_HEADERS },
  });
}

// ─── API Router ───

async function handleRequest(request, env) {
  const url = new URL(request.url);
  const path = url.pathname;

  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: CORS_HEADERS });
  }

  try {
    if (path === "/api/generate") {
      return await handleGenerate(env);
    }
    if (path === "/api/restore") {
      return await handleRestore(request, env);
    }
    if (path === "/api/check") {
      const email = url.searchParams.get("email");
      return await handleCheck(email, env);
    }

    const inboxMatch = path.match(/^\/api\/inbox\/(.+)$/);
    if (inboxMatch) {
      const email = decodeURIComponent(inboxMatch[1]);
      return await handleInbox(email, env);
    }

    const mailMatch = path.match(/^\/api\/mail\/([^/]+)\/(.+)$/);
    if (mailMatch) {
      const email = decodeURIComponent(mailMatch[1]);
      const messageId = decodeURIComponent(mailMatch[2]);
      return await handleReadMail(email, messageId, env);
    }

    return json({ error: "Not found" }, 404);
  } catch (err) {
    return json({ error: err.message || "Internal error" }, 500);
  }
}

// ─── Generate Email (from pool) ───

async function handleGenerate(env) {
  const domain = env.DOMAIN || "tempdomain.com";

  // Try up to 30 random picks to find an unused username
  for (let attempt = 0; attempt < 30; attempt++) {
    const idx = Math.floor(Math.random() * USERNAME_POOL.length);
    const username = USERNAME_POOL[idx];
    const email = `${username}@${domain}`;

    // Check if already taken
    const existing = await env.MAIL_STORAGE.get(`addr:${email}`);
    if (existing) continue;

    // Claim this address
    await env.MAIL_STORAGE.put(`addr:${email}`, JSON.stringify({
      email,
      username,
      created: Date.now(),
    }), { expirationTtl: ADDRESS_TTL });

    // Init empty inbox (30min TTL)
    await env.MAIL_STORAGE.put(`inbox:${email}`, JSON.stringify([]), {
      expirationTtl: EMAIL_TTL,
    });

    return json({ email, username, expiresIn: EMAIL_TTL });
  }

  return json({ error: "No available usernames. Try again." }, 503);
}

// ─── Restore Email ───

async function handleRestore(request, env) {
  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: "Invalid JSON body" }, 400);
  }

  const email = (body.email || "").trim().toLowerCase();
  if (!email || !email.includes("@")) {
    return json({ error: "Invalid email address" }, 400);
  }

  const addrRaw = await env.MAIL_STORAGE.get(`addr:${email}`);
  if (!addrRaw) {
    return json({ error: "Email not found. This address was never generated." }, 404);
  }

  // Reset inbox with fresh 30min TTL
  await env.MAIL_STORAGE.put(`inbox:${email}`, JSON.stringify([]), {
    expirationTtl: EMAIL_TTL,
  });

  // Refresh address TTL
  const addr = JSON.parse(addrRaw);
  await env.MAIL_STORAGE.put(`addr:${email}`, JSON.stringify({
    ...addr,
    restored: Date.now(),
  }), { expirationTtl: ADDRESS_TTL });

  return json({ email, expiresIn: EMAIL_TTL });
}

// ─── Check if email exists ───

async function handleCheck(email, env) {
  if (!email) return json({ error: "Missing email param" }, 400);
  const addrRaw = await env.MAIL_STORAGE.get(`addr:${email}`);
  return json({ email, exists: !!addrRaw });
}

// ─── Check Inbox ───

async function handleInbox(email, env) {
  const inboxRaw = await env.MAIL_STORAGE.get(`inbox:${email}`);
  if (!inboxRaw) {
    // Address exists but inbox expired — recreate
    const addrRaw = await env.MAIL_STORAGE.get(`addr:${email}`);
    if (addrRaw) {
      await env.MAIL_STORAGE.put(`inbox:${email}`, JSON.stringify([]), {
        expirationTtl: EMAIL_TTL,
      });
      return json({ email, messages: [], expiresIn: EMAIL_TTL, refreshed: true });
    }
    return json({ email, messages: [], expiresIn: 0, notFound: true });
  }

  const messageIds = JSON.parse(inboxRaw);
  const messages = [];

  for (const msgId of messageIds) {
    const mailRaw = await env.MAIL_STORAGE.get(`mail:${email}:${msgId}`);
    if (mailRaw) {
      const mail = JSON.parse(mailRaw);
      messages.push({
        id: mail.messageId,
        from: mail.from,
        subject: mail.subject,
        snippet: (mail.textBody || "").substring(0, 120),
        timestamp: mail.timestamp,
      });
    }
  }

  messages.sort((a, b) => b.timestamp - a.timestamp);

  return json({ email, messages, expiresIn: EMAIL_TTL });
}

// ─── Read Email ───

async function handleReadMail(email, messageId, env) {
  const mailRaw = await env.MAIL_STORAGE.get(`mail:${email}:${messageId}`);
  if (!mailRaw) {
    return json({ error: "Email not found or expired" }, 404);
  }
  return json(JSON.parse(mailRaw));
}

// ─── Email Inbound Handler ───

async function handleEmail(message, env) {
  const to = message.to;
  const from = message.from;
  const subject = message.headers.get("subject") || "(no subject)";
  const messageId = message.headers.get("message-id") || `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

  const addrRaw = await env.MAIL_STORAGE.get(`addr:${to}`);
  if (!addrRaw) return;

  let textBody = "";
  let htmlBody = "";

  try {
    const rawBody = await message.text();
    const contentType = message.headers.get("content-type") || "";

    if (contentType.includes("multipart/")) {
      const boundary = contentType.match(/boundary="?([^";\s]+)"?/);
      if (boundary) {
        const parts = rawBody.split(`--${boundary[1]}`);
        for (const part of parts) {
          if (part.includes("text/plain") && !textBody) {
            const bodyStart = part.indexOf("\r\n\r\n");
            if (bodyStart !== -1) {
              textBody = part.substring(bodyStart + 4).trim();
              if (textBody.endsWith("--")) textBody = textBody.slice(0, -2).trim();
            }
          } else if (part.includes("text/html") && !htmlBody) {
            const bodyStart = part.indexOf("\r\n\r\n");
            if (bodyStart !== -1) {
              htmlBody = part.substring(bodyStart + 4).trim();
              if (htmlBody.endsWith("--")) htmlBody = htmlBody.slice(0, -2).trim();
            }
          }
        }
      }
    }

    if (!textBody && !htmlBody) {
      textBody = rawBody;
    }
  } catch (e) {
    textBody = "(error reading email body)";
  }

  const cleanId = messageId.replace(/[<>]/g, "").replace(/[^a-zA-Z0-9._@-]/g, "_");

  const emailData = {
    messageId: cleanId,
    from,
    to,
    subject,
    textBody,
    htmlBody,
    timestamp: Date.now(),
  };

  await env.MAIL_STORAGE.put(`mail:${to}:${cleanId}`, JSON.stringify(emailData), {
    expirationTtl: EMAIL_TTL,
  });

  let inboxIds = [];
  const inboxRaw = await env.MAIL_STORAGE.get(`inbox:${to}`);
  if (inboxRaw) {
    try { inboxIds = JSON.parse(inboxRaw); } catch {}
  }

  if (!inboxIds.includes(cleanId)) {
    inboxIds.push(cleanId);
  }

  await env.MAIL_STORAGE.put(`inbox:${to}`, JSON.stringify(inboxIds), {
    expirationTtl: EMAIL_TTL,
  });
}

// ─── Worker Entry ───

export default {
  fetch: handleRequest,
};

export { handleEmail as email };
